In [5]:
import numpy as np

In [18]:
a = np.array([[1.1, 2.2, 3],
              [4, 5, 6]])

In [21]:
# array 정보
print("value")
print(a)
print("type 변환")
print(a.astype(np.int32))
print("shape", a.shape)
print("ndim", a.ndim)
print("type", a.dtype)
# int, float, bool, complex, object => bit 수를 낮춰 대용량 데이터를 다룰 때 이점을 얻을 수 있음

value
[[1.1 2.2 3. ]
 [4.  5.  6. ]]
type 변환
[[1 2 3]
 [4 5 6]]
shape (2, 3)
ndim 2
type float64


In [24]:
# axis 개념
print("origin", a.shape)
print("axis 0 sum", np.sum(a, axis = 0).shape)
print("axis 1 sum", np.sum(a, axis = 1).shape)

origin (2, 3)
axis 0 sum (3,)
axis 1 sum (2,)


In [37]:
# ndarray 생성 및 변환

print(np.arange(10, 20))
print(np.zeros((2, 3)))
print(np.ones((2, 2)))
print(np.ones((2,2)).reshape(-1))

[10 11 12 13 14 15 16 17 18 19]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[1. 1. 1. 1.]


In [53]:
# 인덱싱

array1d = np.arange(5) * 3
print(array1d)

print(array1d[0:3]) # index 0~2 값들 가져옴
print(array1d[[2, 4]]) # index set에 해당하는 값들 가져옴

array2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print(array2d[[0, 2], :2]) # 0, 2번 행에서 0, 1 열을 가져온다.
print(array2d[array2d > 5]) # boolean indexing => True인 index만 기억 후 fancy indexing으로 가져옴

[ 0  3  6  9 12]
[0 3 6]
[ 6 12]
[[1 2]
 [7 8]]
[6 7 8 9]


In [61]:
# 배열 정렬

a = np.array([1, 5, 3, 6, 8, 3, 2, 6, 10])
b = np.array([[1, 5, 3, 6], [8, 3, 2, 6]])

print(np.sort(a))

a.sort() # in-place
print(a)
print(a[::-1]) # 내림차순 (역순)

print(np.sort(b, axis = 0))
print(np.sort(b, axis = 1))

print(np.argsort(b)) # 값으로 정렬 후, 값의 원래 index들을 뽑아냄

# name_array = {"John", "Mike", "Kate"}
# score_array = {10, 20, 15}
# John = 10, Mike = 20, Kate = 15인데 index를 바탕으로 연관이 있으므로 argsort로 하면 편함

[ 1  2  3  3  5  6  6  8 10]
[ 1  2  3  3  5  6  6  8 10]
[10  8  6  6  5  3  3  2  1]
[[1 3 2 6]
 [8 5 3 6]]
[[1 3 5 6]
 [2 3 6 8]]
[[0 2 1 3]
 [2 1 3 0]]


In [63]:
# 선형대수 연산

a = np.array([[1, 2], [3, 4]])
b = np.array([[1], [2]])
print(np.dot(a,b))
print(np.transpose(a))

[[ 5]
 [11]]
[[1 3]
 [2 4]]
